### PR TITLE
lit: fix example ports

### PR DESCRIPTION
**Pull request by guggero**
Pull Request Checklist
- [X] The documents updated are not in the `docs/` directory. These files are
  synced from upstream repositories ([lnd](https://github.com/lightningnetwork/lnd), [lit](https://github.com/lightninglabs/lightning-terminal), [loop](https://github.com/lightninglabs/loop), [pool](https://github.com/lightninglabs/pool) and [faraday](https://github.com/lightninglabs/faraday)), and 
  should be updated in their parent repo.

cc @Liongrass

### CODE REVIEW

**Review by ryanthegentry — APPROVED** [review]
LGTM, thank you Oli!

**Review by jamaljsr — APPROVED** [review]
The modifications LGTM.

@ryanthegentry Aren't these docs supposed to be synced from the source repo? Is that not happening any longer?

I also vaguely remember there being an issue in the past where the images will break if we manually modify the files in this repo that are automatically being synced.

**Comment by ryanthegentry** [comment]
These particular docs don't exist in the source repo, they were initialized in Gitbook. If useful, maybe we could put them in the source repo?

**Comment by jamaljsr** [comment]
Ahhh, my bad. I mistook these guides with the install instructions in the repo. There is some overlap, they are different. ￼

I agree about merging into a single source but i think it would be easier to manage if it only lived in Gitbook instead of the LiT repo. This way, you and Leo can modify it much easier when necessary.

**Comment by Liongrass** [comment]
Personally I'd favor simple installation instructions in a readme and links to the guides. It's indeed far easier to update in gitbook, and creating too many cross-dependencies risks introducing bugs like the empty pages or missing images

**Comment by jamaljsr** [comment]
> Personally I'd favor simple installation instructions in a readme and links to the guides. It's indeed far easier to update in gitbook, and creating too many cross-dependencies risks introducing bugs like the empty pages or missing images

cosign 👍

**Comment by ryanthegentry** [comment]
Cool let's leave as-is then 👍

**Pull request merged**
